const codigoCiudad = {
    "Puebla": 2,
    "Veracruz": 2,
    "Tlaxcala": 2,
    "Hidalgo": 2,
    "Jalisco": 3,
    "Colima": 3,
    "Nayarit": 3,
    "Zacatecas": 4,
    "San Luis Potosí": 4,
    "Aguascalientes": 4,
    "Guanajuato": 4,
    "Querétaro": 4,
    "Michoacán": 4,
    "Ciudad de México": 5,
    "Estado de México": 5,
    "Sinaloa": 6,
    "Durango": 6,
    "Chihuahua": 6,
    "Sonora": 6,
    "Baja California": 6,
    "Baja California Sur": 6,
    "Guerrero": 7,
    "Morelos": 7,
    "Coahuila": 8,
    "Nuevo León": 8,
    "Tamaulipas": 8,
    "Oaxaca": 9,
    "Chiapas": 9,
    "Tabasco": 9,
    "Campeche": 9,
    "Yucatán": 9,
    "Quintana Roo": 9
};

const DAYS_PER_MONTH = {
    1: 31,
    2: 28,
    3: 31,
    4: 30,
    5: 31,
    6: 30,
    7: 31,
    8: 31,
    9: 30,
    10: 31,
    11: 30,
    12: 31
};
